# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.box = "ubuntu/focal64"
    server.vm.network "private_network", ip: "192.168.56.34"
    server.vm.provision "shell", path: "server.sh"
  end
  
  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.box = "ubuntu/focal64"
    client.vm.network "private_network", ip: "192.168.56.33"
    client.vm.provision "shell", path: "client.sh"
  end
end

