#!/bin/bash

DB_HOST=127.0.0.1
DB_NAME=db_name
DB_USER=db_user
DB_PASSWORD="AZ2iony6HAFtioaCRUJ3Zh5izcZ"

sudo apt update -y
sudo apt upgrade -y
sudo apt install -y mysql-server

sudo mysql --user="root"  -e "
CREATE SCHEMA IF NOT EXISTS ${DB_NAME};
CREATE USER IF NOT EXISTS '${DB_USER}'@'${DB_HOST}' IDENTIFIED BY '${DB_PASSWORD}';
GRANT ALL ON ${DB_NAME}.* TO '${DB_USER}'@'${DB_HOST}';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE ${DB_NAME}.* TO '${DB_USER}'@'${DB_HOST}';
FLUSH PRIVILEGES;
USE ${DB_NAME};
CREATE TABLE users (
  id int NOT NULL AUTO_INCREMENT,
  login varchar(256) NOT NULL,
  password varchar(256) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY users_login_UNIQUE (login)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO users VALUES (1,'admin','password'),(2,'user','password2');
CREATE TABLE posts (
  id int NOT NULL AUTO_INCREMENT,
  id_users varchar(256) NOT NULL,
  title varchar(256) NOT NULL,
  text varchar(256) NOT NULL,
  is_deleted tinyint DEFAULT '0',
  PRIMARY KEY (id)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
INSERT INTO posts VALUES (1,1,'title','text',0),(2,2,'title2','text2',0);
"

sudo tee /opt/backup.sh &>/dev/null <<EOF
#!/bin/bash
sudo mysqldump -u root -h localhost ${DB_NAME} > "/opt/mysql_backup/${DB_NAME}_\$(date -d "today" +"%Y-%m-%d-%H-%M").sql"

find /opt/mysql_backup/ -name '${DB_NAME}_*' -mtime +5 -exec rm {} \;

EOF

sudo chmod +x /opt/backup.sh

sudo mkdir -p /opt/mysql_backup

sudo tee /var/spool/cron/crontabs/root &>/dev/null <<EOF
# DO NOT EDIT THIS FILE - edit the master and reinstall.
# (/tmp/crontab.8rvV6n/crontab installed on Thu Nov 30 02:48:47 2023)
# (Cron version -- $Id: crontab.c,v 2.13 1994/01/17 03:20:37 vixie Exp \$)
# Edit this file to introduce tasks to be run by cron.
# 
# Each task to run has to be defined through a single line
# indicating with different fields when the task will be run
# and what command to run for the task
# 
# To define the time you can provide concrete values for
# minute (m), hour (h), day of month (dom), month (mon),
# and day of week (dow) or use '*' in these fields (for 'any').
# 
# Notice that tasks will be started based on the cron's system
# daemon's notion of time and timezones.
# 
# Output of the crontab jobs (including errors) is sent through
# email to the user the crontab file belongs to (unless redirected).
# 
# For example, you can run a backup of all your user accounts
# at 5 a.m every week with:
# 0 5 * * 1 tar -zcf /var/backups/home.tgz /home/
# 
# For more information see the manual pages of crontab(5) and cron(8)
# 
# m h  dom mon dow   command
0 0 * * * /usr/bin/bash /opt/backup.sh

EOF

sudo apt install -y openssh-server

DIR=/home/vagrant/.ssh

ssh-keygen -t ed25519 -C "test@test.com" -f $DIR/id_rsa -N ""

chown -R vagrant:vagrant $DIR

cp $DIR/id_rsa.pub /vagrant/authorized_keys

echo -e "\n192.168.56.34 store\n" >> /etc/hosts

sudo apt install -y rsync

sudo tee /opt/rsync.sh &>/dev/null <<EOF
rsync -aPe "ssh -i /home/vagrant/.ssh/id_rsa" /opt/mysql_backup/ vagrant@store:/opt/store/mysql
EOF

sudo chmod +x /opt/rsync.sh

